### ISSUE TITLE
Toggling fullscreen on big buck bunny doesn't work

### ISSUE THREAD

**Issue by stuaxo** [munezbn/dispmanx-gst-play#2]
Hi,
    I was testing big buck bunny which comes with the pi.    If you toggle full screen, the screen goes black.

$ GST_DEBUG=3 ./dispmanx-gst-play --interactive /opt/vc/src/hello_pi/hello_video/test.h264

Press F

**Comment by stuaxo** [comment]
```
Current subtitle track: 
[WARNING] : dispmanx-gst-play.c -> media_info_cb(342) : ?????????? Video Resolution Changed ?????????? 0 0 ==> 1920 1080
[INFO]    : dispmanx-window.c -> dispmanx_win_set_fullscreen(280) : Scaling from 0 0 1920 1080 ==> 0 289 480 270
State changed: playing
[TRACE]   : dispmanx-gst-play.c -> keyboard_cb(680) : Un-FullScreen
[INFO]    : dispmanx-window.c -> dispmanx_win_set_fullscreen(280) : Scaling from 0 0 1920 1080 ==> 2147482928 2147483532 1920 1080
[TRACE]   : dispmanx-gst-play.c -> keyboard_cb(685) : FullScreen
[INFO]    : dispmanx-window.c -> dispmanx_win_set_fullscreen(280) : Scaling from 0 0 1920 1080 ==> 0 289 480 270
```

**Comment by munezbn** [comment]
I have changed the design and implementation of sample app with  feba25ab8bf9c469f5bdd9d91dd0987fe8beef35

I tried same video and i didnt face any issues with new implementation

**Comment by stuaxo** [comment]
It's been a few years since I worked on raspberry pi + video playing, but want to say thanks for this project.
